import Providers from "@/components/Providers";
import "./globals.css";

export const metadata = {
  title: "Notes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='bg-gray-100'>
        <Providers>
          <div className='max-w-[1500px] mx-auto w-full px-3 sm:px-16 lg:px-32'>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
